apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: collector-shop
data:
  DATABASE_URL: "file:./dev.db"
  FRONTEND_URL: "http://9.223.210.37"
  RABBITMQ_URL: "amqp://admin:admin123@rabbitmq.collector-shop.svc.cluster.local:5672"
