apiVersion: v1
kind: Service
metadata:
  name: collector-backend
  namespace: collector-shop
  labels:
    app: collector-backend
spec:
  type: NodePort
  selector:
    app: collector-backend
  ports:
    - name: http
      port: 4003
      targetPort: 4003
      nodePort: 30003
