apiVersion: v1
kind: Service
metadata:
  name: collector-frontend
  namespace: collector-shop
  labels:
    app: collector-frontend
spec:
  type: NodePort
  selector:
    app: collector-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
