apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collector-shop-ingress
  namespace: collector-shop
spec:
  ingressClassName: nginx
  rules:
    - host: collector-shop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collector-frontend
                port:
                  number: 80
